DCCNews/urls.py
from NoticiasDCC import settings

__author__ = 'milenkotomic'
from django.conf.urls import patterns, url
from DCCNews import views

urlpatterns = patterns('',
                       url(r'^login/', views.login_view, name='login'),
                       url(r'^logout/', views.logout_view, name='logout'),
                       url(r'^index/', views.index, name='index'),
                       url(r'^publication/new/template', views.select_template, name='template_selection'),
                       url(r'^slide/new/(?P<template_id>\d+)', views.new_slide, name='new_slide'),
                       url(r'^slide/edit/(?P<publication_id>\d+)/', views.edit_slide, name='edit_slide'),
                       url(r'^event/new/(?P<template_id>\d+)', views.new_event, name='new_event'),
                       url(r'^event/edit/(?P<publication_id>\d+)/', views.edit_event, name='edit_event'),
                       url(r'^createtag/', views.create_tag, name='createTag'),
                       url(r'^deletetag/', views.delete_tag, name='deleteTag'),
                       url(r'^savedraft/(?P<template_id>\d+)/', views.save_draft, name='save_draft'),
                       url(r'^loaddraft/', views.load_draft, name='load_draft'),

                       url(r'^$', views.index, name='index'),
                       url(r'^search/slide/', views.search_slide, name='search_slide'),#pagina de busqueda de diapositivas
                       url(r'^search/event/', views.search_event, name='search_event'),#pagina de busqueda de eventos
                       url(r'^visualize/(?P<template_id>\d+)', views.visualize, name='visualize_content'),
                       url(r'^update/', views.update_news, name='update_content'),
                       )

NoticiasDCC/urls.py
from NoticiasDCC import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'NoticiasDCC.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^news/', include('DCCNews.urls')),
    url(r'^$', include('DCCNews.urls')),
]

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

DCCNews/models.py
from django.db import models
from django.contrib.auth.models import User
import os


class Type(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class Template(models.Model):
    name = models.CharField(max_length=100)
    view = models.CharField(max_length=400)
    view_prev = models.CharField(max_length=400)

    def __unicode__(self):
        return self.name


class Priority(models.Model):
    name = models.CharField(max_length=100)
    frequency = models.IntegerField(default=50)

    def __unicode__(self):
        return self.name


class Publication(models.Model):
    type_id = models.ForeignKey(Type)
    tag_id = models.ForeignKey(Tag)
    user_id = models.ForeignKey(User)
    template_id = models.ForeignKey(Template)
    priority_id = models.ForeignKey(Priority)
    init_date = models.DateTimeField()
    end_date = models.DateTimeField()
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_user_id = models.ForeignKey(User, related_name="modification_user")
    modification_date = models.DateTimeField(auto_now_add=True)


class Image(models.Model):
    image = models.ImageField(upload_to='images')
    number = models.IntegerField()
    publication_id = models.ForeignKey(Publication)

    def __unicode__(self):
        return os.path.basename(self.image.name)

    def save(self, *args, **kwargs):
        if self.image:
            self.image.name = self.image.name.encode('ascii', 'ignore')
        super(Image, self).save(*args, **kwargs)


class Temp(models.Model):
    image = models.ImageField(upload_to='temp')

    def save(self, *args, **kwargs):
        if self.image:
            self.image.name = self.image.name.encode('ascii', 'ignore')
        super(Temp, self).save(*args, **kwargs)

class Text(models.Model):
    text = models.TextField()
    number = models.IntegerField()
    publication_id = models.ForeignKey(Publication)

    def __unicode__(self):
        return self.text

DCCNews/forms.py
# -*- coding: utf-8 -*-
from DCCNews.models import Tag

__author__ = 'milenkotomic'


from django import forms
from django.forms import Form, ModelForm


class MyDateTimeInput(forms.DateInput):
    input_type = 'datetime-local'


class MyTimeInput(forms.DateInput):
    input_type = 'time'


class MyDateInput(forms.DateInput):
    input_type = 'date'

#class myCountTextArea(forms.CharField):
    

# Formulario para inicio de sesión
class LoginForm(Form):
    user = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Usuario',
                                                                        'class': 'form-control'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña',
                                                                                'class': 'form-control'}))


class TagCreationForm(Form):
    new_tag = forms.CharField(max_length=11,
                              required=False,
                              widget=forms.TextInput(attrs={'class': 'form-control',
                                                            'display': 'block'}),
                              label='Ingrese tag')


class PublicationForm(Form):
    start_circulation = forms.DateField(required=True,
                                        widget=forms.TextInput(attrs={'class': 'form-control',
                                                                      'placeholder': 'DD-MM-AAAA',
                                                                      'onChange': 'checkCirculation()'}),
                                        label='Inicio de Circulación',
                                        input_formats=['%d-%m-%Y',
                                                       '%Y-%m-%d'])

    start_circulation_time = forms.TimeField(required=True,
                                             widget=MyTimeInput(attrs={'class': 'form-control',
                                                                       'placeholder': 'HH:MM',
                                                                       'onChange': 'checkCirculation()',
                                                                       'onfocus': 'defaultTime(this)'}),
                                             label='Inicio de Circulación',
                                             input_formats=['%H:%M'])

    end_circulation = forms.DateField(required=True,
                                      widget=forms.TextInput(attrs={'class': 'form-control',
                                                                    'placeholder': 'DD-MM-AAAA',
                                                                    'onChange': 'checkCirculation()'}),
                                      label='Fin de Circulación',
                                      input_formats=['%d-%m-%Y',
                                                     '%Y-%m-%d'])

    end_circulation_time = forms.TimeField(required=True,
                                           widget=MyTimeInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'HH:MM',
                                                                     'onChange': 'checkCirculation()',
                                                                     'onfocus': 'defaultTime(this)'}),
                                           label='Fin de Circulación',
                                           input_formats=['%H:%M'])

    slide_type = forms.ModelChoiceField(required=True,
                                        queryset=Tag.objects.all().order_by('name'),
                                        widget=forms.Select(attrs={'class': 'form-control'}),
                                        label='Tipo de Diapositiva')

    img_url = forms.CharField(required=False,
                            widget=forms.TextInput(attrs={'style': 'display: none'}),
                            label='Imagen existente')

    def clean(self):
        cleaned_data = super(PublicationForm, self).clean()
        start_circulation = cleaned_data.get("start_circulation")
        end_circulation = cleaned_data.get("end_circulation")
        start_circulation_time = cleaned_data.get("start_circulation_time")
        end_circulation_time = cleaned_data.get("end_circulation_time")

        if start_circulation:
            if start_circulation.year < 1900:
                msg = 'Fecha inválida'
                self.add_error('start_circulation', msg)

        if end_circulation:
            if end_circulation.year < 1900:
                msg = 'Fecha inválida'
                self.add_error('end_circulation', msg)

        start_circulation = cleaned_data.get("start_circulation")
        end_circulation = cleaned_data.get("end_circulation")

        if start_circulation and end_circulation and start_circulation_time and end_circulation_time:
            if (start_circulation > end_circulation) or \
                    (start_circulation == end_circulation and start_circulation_time >= end_circulation_time):
                msg = 'La fecha de término debe ser posterior a la fecha de inicio'
                self.add_error('start_circulation', msg)
                del self.cleaned_data['end_circulation']


class SlideText(PublicationForm):
    title = forms.CharField(#max_length=65,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Título')

    body = forms.CharField(#max_length=1000,
                           required=True,
                           widget=forms.Textarea(attrs={'class': 'form-control',
                                                        'rows': 4,
                                                        'cols': 40}),
                           label='Cuerpo de la diapositiva')


class SlideImage(PublicationForm):
    title = forms.CharField(#max_length=65,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Título')

    image = forms.ImageField(required=True,
                             widget=forms.ClearableFileInput(attrs={'class': 'form-control'}),
                             label='Imagen')


class SlideGraduation(PublicationForm):
    title = forms.CharField(#max_length=65,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Título')

    subhead = forms.CharField(#max_length=100,
                              required=True,
                              widget=forms.TextInput(attrs={'class': 'form-control'}),
                              label='Bajada de Título')

    image = forms.ImageField(required=True,
                             widget=forms.ClearableFileInput(attrs={'class': 'form-control'}),
                             label='Imagen')


class SlideImageText(PublicationForm):
    title = forms.CharField(#max_length=65,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Título')

    body = forms.CharField(#max_length=1000,
                           required=True,
                           widget=forms.Textarea(attrs={'class': 'form-control',
                                                        'rows': 4,
                                                        'cols': 40}),
                           label='Cuerpo de la diapositiva')

    image = forms.ImageField(required=True,
                             widget=forms.ClearableFileInput(attrs={'class': 'form-control'}),
                             label='Imagen')


class EventForm(PublicationForm):
    title = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Título')

    exhibitor = forms.CharField(max_length=100,
                                required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control'}),
                                label='Expositor')

    date = forms.DateField(required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': 'DD-MM-AAAA'}),
                           label='Fecha',
                           input_formats=['%d-%m-%Y',
                                          '%Y-%m-%d'])

    time = forms.TimeField(required=True,
                           widget=MyTimeInput(attrs={'class': 'form-control',
                                                     'placeholder': 'HH:MM',
                                                     'onfocus': 'defaultTime(this)'}),
                           label='Hora',
                           input_formats=['%H:%M'])

    place = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control'}),
                            label='Lugar')


class EventImage(EventForm):
    image = forms.ImageField(required=True,
                             widget=forms.ClearableFileInput(attrs={'class': 'form-control'}),
                             label='Imagen')


class TagForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                           label='Nombre')

    class Meta:
        model = Tag
        fields = ['name']


#El formulario padre, en particular el titulo para busqueda
class SearchElement(Form):
    #input del titulo
    titulo = forms.CharField(required=False,

DCCNews/templates/DCCNews/index.html
{% extends "DCCNews/base.html" %}
{% load staticfiles %}
{% block content %}
    {% if create %}
        <div class="alert alert-success" role="alert">El contenido se ha guardado de forma exitosa.</div>
    {% endif %}
    {% if login %}
        <div class="alert alert-warning" role="alert">Ya hay una sesión iniciada.</div>
    {% endif %}

    <h1>Bienvenido a Noticias DCC</h1>
    <h2>Seleccione la actividad que desea realizar</h2>
    <hr style="width: 100%; color: black; height: 1px; background-color:black;" />
    <legend ALIGN=center >Creación de Contenido</legend>
    <row >
        <div class="btn-group btn-group-justified" >
            <a href="{% url 'template_selection' %}" class="btn btn-primary btn-lg btn-block" role="button">Crear</a>
        </div>
    </row>
    <hr style="width: 100%; color: black; height: 1px; background-color:black;" />
    <legend ALIGN=center>Búsqueda de contenido</legend>
    <row>
        <div class="btn-group btn-group-justified" >
            <a href="{% url 'search_event' %}"  class="btn btn-primary btn-lg btn-block" role="button">Evento</a>
            <a href="{% url 'search_slide' %}"  class="btn btn-primary btn-lg btn-block" role="button">Diapositiva</a>
        </div>
    </row>
    <hr style="width: 100%; color: black; height: 0.5px; background-color:black;" />
    <legend ALIGN=center>Visualización de Display</legend>
    <row>
        <div class="btn-group btn-group-justified" >
            <a href="/news/visualize/1" class="btn btn-info btn-lg btn-block" role="button">Ver ahora</a>
        </div>
    </row>

{% endblock %}

DCCNews/templates/DCCNews/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Sistemas de Noticias DCC</title>

    <link rel="stylesheet" href="{% static 'DCCNews/style/bootstrap.css' %}">
    <link href="{% static 'DCCNews/style/login.css' %}" rel="stylesheet">
    <script src="{% static 'DCCNews/js/jquery.min.js' %}"></script>
    <script src="{% static 'DCCNews/js/bootstrap.js' %}"></script>
    <script language="JavaScript">
        function checkLogin(){
            var username = $("#id_user").val().trim();
            var password = $("#id_password").val().trim();
            if (username == "" || password == ""){
                $("#error-message").html("Debe ingresar usuario y contraseña")
                return false;
            }
            return true;
        }
    </script>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>
<body>
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">
                <h1 class="cover-heading">Noticias DCC</h1>

                <span id="error-message" class="login-error-message">{{ error_message }}</span>
                <span class="login-notify-message">{{ notify_message }}</span>

                <form action="{% url 'login' %}" method="POST" class="form-signin" role="form" onsubmit="return checkLogin()">
                    {% csrf_token %}
                    {{ form.user }}
                    {{ form.password }}
                    <button class="btn btn-lg btn-warning btn-block" type="submit">Entrar</button>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

DCCNews/templates/DCCNews/slide.html
{% extends "DCCNews/base.html" %}
{% load staticfiles %}

{% block head %}
    <script src="{% static 'DCCNews/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'DCCNews/js/DateTimePickers.js' %}"></script>
    <script src="{% static 'DCCNews/js/es.js' %}"></script>
    <link rel="stylesheet" href="{% static 'DCCNews/style/bootstrap-datetimepicker.css' %}" />
    <script src="{% static 'DCCNews/js/utilities.js' %}"></script>
    <script src="{% static 'DCCNews/js/changeForm.js' %}"></script>
    <script src="{% static 'DCCNews/js/tag_administration.js' %}"></script>
    <script src="{% static 'DCCNews/js/jquery.form.js' %}"></script>
    <script src="{% static 'DCCNews/js/bootstrap-maxlength.js' %}"></script> <!-- script base para los contadores de caracteres -->
    <script src="{% static 'DCCNews/js/counter.js' %}"></script> <!-- Script que pasa por los formularios agregando el texto de ayuda con los caracteres que le faltan -->
	<script src="{% static 'DCCNews/js/tinymce/js/tinymce/tinymce.js' %}"></script> <!-- agrega la base para los textos enriquecidos  -->
	<script src="{% static 'DCCNews/js/initTextEn.js' %}"></script><!--  Script que cambia los textarea y input correctos por tinyMCE -->
    <script>
        function createTagSuccess(result) {
            var tagSelect = JSON.parse(JSON.stringify(result.tags));
            var text = JSON.parse(JSON.stringify(result.text));
            $("#tags").empty();
            $("#tags").html(tagSelect);
            $("#new_tag").hide();
            alert(text);
        }

        function deleteTagSuccess(result) {
            var tagSelect = JSON.parse(JSON.stringify(result.tags));
            $("#tags").empty();
            $("#tags").html(tagSelect);
            $("#new_tag").hide();
            var deleted = JSON.parse(JSON.stringify(result.deleted_tag));
            if (deleted)
                alert("Tag borrado exitosamente");
            else
                alert("Este tag no puede ser borrado");
        }

        function sendNewTag(){
            var name = $("#id_new_tag").val();
            var data = {new_tag: name, csrfmiddlewaretoken: "{{ csrf_token }}"};
            if (name.trim().length != 0)
                ajaxCall("{% url 'createTag' %}" , data, createTagSuccess );
            else
                alert("Nuevo tag inválido");
        }

        function deleteTag(){
            var tag = $("#id_slide_type").val();
            var data = {tag: tag, csrfmiddlewaretoken: "{{ csrf_token }}"};
            ajaxCall("{% url 'deleteTag' %}" , data, deleteTagSuccess );
        }

        {% if new %}
        window.setInterval( function() {
        	//recorre todos los textos de area enriquecidos y los manda a los textarea que remplaza
        	for (edId in tinyMCE.editors)
        	    tinyMCE.editors[edId].save();
            saveDraft({{ template }})
        }, 5000);
        {% endif %}
    </script>
{% endblock %}

{% block content %}
    {% if new %}
        <legend>Creación de diapositiva</legend>
    {% else %}
        <legend>Edición de diapositiva</legend>
    {% endif %}
    {% if mensaje %}
        <div class="col-lg-12">
            <div class="alert alert-success" role="alert">Cambios guardados de forma exitosa</div>
        </div>
    {% endif %}
    <div class="col-lg-6 col-md-9">
        <form action="" method="post" enctype="multipart/form-data" name="form" id="formID" onsubmit="return validateForms()">
            {% csrf_token %}
            {% if form.title %}
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <label class="col-lg-5 col-md-5 control-label">{{ form.title.label }}:</label>
                                <div class="col-lg-7 col-md-5 text-danger text-right">{{ form.title.errors.as_text }}</div>
                            </div>
                            {{ form.title }}
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if form.subhead %}
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <label class="col-lg-5 col-md-5 control-label">{{ form.subhead.label }}:</label>
                                <div class="col-lg-7 col-md-5 text-danger text-right">{{ form.subhead.errors.as_text }}</div>
                            </div>
                            {{ form.subhead }}
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if form.body %}
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <label class="col-lg-5 col-md-5 control-label">{{ form.body.label }}:</label>
                                <div class="col-lg-7 col-md-5 text-danger text-right">{{ form.body.errors.as_text }}</div>
                            </div>
                            {{ form.body }}
                        </div>
                    </div>
                </div>
            {% endif %}

            {% if form.image %}
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <label class="col-lg-5 col-md-5 control-label">{{ form.image.label }}:</label>
                                <div class="col-lg-7 col-md-5 text-danger text-right">{{ form.image.errors.as_text }}</div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    {% if not new %}
                                        <em>Imagen Actual:</em>
                                        <em style="color: #0000c8"> {{ image_name }}</em>
                                    {% endif %}
                                </div>
                            </div>

                            {{ form.image }}
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-5 col-md-5 control-label">{{ form.start_circulation.label }}:</label>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                {{ form.start_circulation }}
                                <div class="text-danger">{{ form.start_circulation.errors.as_text }}</div>
                            </div>
                            <div class="col-lg-6">
                                {{ form.start_circulation_time }}
                                <div class="text-danger">{{ form.start_circulation_time.errors.as_text }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-5 col-md-5 control-label">{{ form.end_circulation.label }}:</label>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                {{ form.end_circulation }}
                                <div class="text-danger">{{ form.end_circulation.errors.as_text }}</div>
                            </div>
                            <div class="col-lg-6">
                                {{ form.end_circulation_time }}
                                <div class="text-danger">{{ form.end_circulation_time.errors.as_text }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-5 col-md-5 control-label">{{ form.slide_type.label }}:</label>
                            <div class="col-lg-7 col-md-5 text-danger text-right">{{ form.slide_type.errors.as_text }}</div>
                        </div>
                        {% if new %}
                        <div class="row">
                            <div id="tags" class="col-lg-8 col-md-8">
                                {% include "DCCNews/tags.html" %}
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <button class="btn btn-danger" type="button" onclick="deleteTag()">Borrar</button>
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <button class="btn btn-info" type="button" onclick="addTag()">Agregar</button>
                            </div>
                        </div>
                        <br>
                        <div id="new_tag" class="row" style="display: none;">
                            <div class="col-lg-10">
                                {{ tagForm.new_tag }}
                            </div>
                            <div class="col-lg-2 col-md-2">
                                <button class="btn btn-success" type="button" onclick="sendNewTag()">Guardar</button>
                            </div>
                        </div>
                        {% else %}
                            {% include 'DCCNews/tags.html' %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="form-group">
                        {{ form.img_url }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="form-group">
                        <button id="saveButton" class="btn btn-success" onclick="goToSave()" type="submit">Guardar</button>
                        {% if new %}
                            <a href="{% url 'index' %}" class="btn btn-danger" onClick="return confirm('¿Esta seguro que desea cancelar?')">Cancelar</a>
                        {% else %}
                            <a href="{% url 'search_slide' %}?cancel=1" class="btn btn-danger" onClick="return confirm('¿Esta seguro que desea cancelar?')">Cancelar</a>
                        {% endif %}
                        <button id="prevButton" class="btn btn-info" onclick="goToPrev({{ template }})" type="submit">Previsualizar</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div id="processing" class="col-lg-7 col-md-7" style="display: none;">
                    <div class="form-group">
                        <div class="alert alert-success" role="alert">Procesando. Por favor espere.</div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-lg-offset-1 col-lg-3 text-center col-md-3 hidden-xs hidden-sm">
        <label>Plantilla seleccionada</label>
        <img src="{% static image  %}">
        {% if new %}
            <a href="{% url 'template_selection' %}" class="btn btn-primary">Volver</a>
        {% endif %}
    </div>

{% endblock %}

DCCNews/templates/DCCNews/tags.html
{{ form.slide_type }}

DCCNews/templates/DCCNews/template2.html
<div id="{{slide.id}}" class="imagen new" style="display: none">
        <img src="/media/{{ slide.image }}" height="" width="">
</div>

DCCNews/templates/DCCNews/template4.html
<div  id="{{slide.id}}" class="new" style="display: none">
    <div class="titulo">
        <h2>{{ slide.title|safe }}</h2>
    </div>
    <div class="t-text-i">
        <p>{{ slide.text|safe }}</p>
    </div>

    <div class="t-t-img">
        <img src="/media/{{ slide.image }}" width="" height="" alt=""/>
    </div>
</div>

DCCNews/templates/DCCNews/template5.html
<div class="info">
    <h4>{{ event.title|safe }}</h4>
    <p>{% if event.exhibitor %}<span class="tema">Expositor:</span> {{ event.exhibitor }}{% endif %}<br/>
        <span class="tema">Fecha:</span> {{ event.date|date:"j F" }}<br/>
        <span class="tema">Hora:</span> {{ event.time|time:"H:i" }} <br/>
        <span class="tema">Lugar:</span> {{ event.place }}
    </p>
</div>

DCCNews/templates/DCCNews/template6.html
<div class="info-i">
    <h4>{{ event.title|safe }}</h4>
    <p>{% if event.exhibitor %}<span class="tema">Expositor:</span> {{ event.exhibitor }}{% endif %}<br/>
        <span class="tema">Fecha:</span> {{ event.date|date:"j F" }}<br/>
        <span class="tema">Hora:</span> {{ event.time|time:"H:i" }}<br/>
        <span class="tema">Lugar:</span> {{ event.place }}
    </p>
</div>
<div class="i-img">
    <img src="/media/{{ event.image }}" width="" height="" alt=""/>
</div>